const data = {
    products:[
        {
            _id:'1',
            name: 'Slim Shirt & Pants',
            category: 'Shirt',
            image: './images/p1.jpg',
            pirce: '130',
            brand: 'Nike',
            rating: 5.00,
            numReviews:10,
            description: 'high quality Shirt',
        },
        {
            _id:'2',
            name: 'Shirt & Suit',
            category: 'Suit',
            image: './images/p2.jpg',
            pirce: '330',
            brand: 'Nike',
            rating: 4.50,
            numReviews:30,
            description: 'high quality Suit',
        },
        {
            _id:'3',
            name: 'Suit & Pants',
            category: 'Pants',
            image: './images/p3.jpg',
            pirce: '230',
            brand: 'Nike',
            rating: 3.40,
            numReviews:15,
            description: 'high quality Pants',
        },
        {
            _id:'4',
            name: 'Suit & Shirt',
            category: 'Suit',
            image: './images/p4.jpg',
            pirce: '300',
            brand: 'Nike',
            rating: 4.30,
            numReviews:9,
            description: 'high quality Suit',
        },
        {
            _id:'5',
            name: 'Slim T-Shirt',
            category: 'T-Shirt',
            image: './images/p5.jpg',
            pirce: '320',
            brand: 'Nike',
            rating: 5.00,
            numReviews:20,
            description: 'high quality T-Shirt',
        },
        {
            _id:'6',
            name: 'Slim Suit',
            category: 'Suit',
            image: './images/p6.jpg',
            pirce: '310',
            brand: 'Nike',
            rating: 4.40,
            numReviews:30,
            description: 'high quality Suit',
        },
        {
            _id:'7',
            name: 'Slim Pants',
            category: 'Pants',
            image: './images/p7.jpg',
            pirce: '210',
            brand: 'Nike',
            rating: 4.50,
            numReviews:10,
            description: 'high quality Pants',
        },
        {
            _id:'8',
            name: 'Slim Shirt',
            category: 'Shirt',
            image: './images/p8.jpg',
            pirce: '110',
            brand: 'Nike',
            rating: 4.00,
            numReviews:10,
            description: 'high quality Shirt',
        },
        {
            _id:'9',
            name: ' Slim T-Shirt',
            category: 'T-Shirt',
            image: './images/p9.jpg',
            pirce: '320',
            brand: 'Nike',
            rating: 4.90,
            numReviews:10,
            description: 'high quality T-Shirt',
        },
        {
            _id:'6',
            name: 'Slim Pant',
            category: 'Pant',
            image: './images/p10.jpg',
            pirce: '100',
            brand: 'Nike',
            rating: 5.00,
            numReviews:40,
            description: 'high quality Pant',
        },
    ]
}

export default data;