const data = {
    products:[
        {
            _id:'1',
            name: 'Slim Shirt & Pants',
            category: 'Shirt',
            image: './images/p1.jpg',
            price: '130',
            brand: 'Nike',
            rating: 5.00,
            numReviews:10,
            description: 'high quality Shirt',
        },
        {
            _id:'2',
            name: 'Shirt & Suit',
            category: 'Suit',
            image: './images/p4.jpg',
            pirce: '330',
            brand: 'Nike',
            rating: 4.50,
            numReviews:30,
            description: 'high quality Suit',
        },
        {
            _id:'3',
            name: 'Shirt & Pants',
            category: 'Pants',
            image: './images/p3.jpg',
            pirce: '230',
            brand: 'Nike',
            rating: 3.40,
            numReviews:15,
            description: 'high quality Pants',
        },
        {
            _id:'4',
            name: 'Pants Shoes',
            category: 'Suit',
            image: './images/p4.jpg',
            pirce: '300',
            brand: 'Nike',
            rating: 4.30,
            numReviews:9,
            description: 'high quality Pants & Shoes',
        },
        {
            _id:'5',
            name: 'Pants & Shoes',
            category: 'Pants & Shoes',
            image: './images/p5.jpg',
            pirce: '320',
            brand: 'Nike',
            rating: 5.00,
            numReviews:20,
            description: 'high quality Pants & Shoes',
        },
        {
            _id:'6',
            name: 'Slim Pants',
            category: 'Pants',
            image: './images/p6.jpg',
            pirce: '310',
            brand: 'Nike',
            rating: 4.40,
            numReviews:30,
            description: 'high quality Pants',
        }
    ]
}

export default data;